name: ci

on:
  workflow_dispatch:
  push:
    tags:
      - '*.*.*'

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
    - name: Set - Tag
      id: set-tag
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

    - name: Check out the repo
      uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675
      
    - name: DOCKER - Login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}
        registry: pipelineimages.azurecr.io
    
    - name: DOCKER - Setup QEMU
      uses: docker/setup-qemu-action@v1

    - name: DOCKER - Setup BuildX 
      uses: docker/setup-buildx-action@v1
      
    - name: DOCKER - Build and Push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true 
        file: Dockerfile
        tags: |
          pipelineimages.azurecr.io/utilities/dotnet-ingestion-pipeline:${{ steps.set-tag.outputs.tag }}
          pipelineimages.azurecr.io/utilities/dotnet-ingestion-pipeline:latest